# action.yml
name: "Wait on check"
author: "progapandist"
description: "Wait on a certain check to pass for commit"
inputs:
  allowed-conclusions:
    description: "Array of allowed conclusions"
    required: false
    default: success,skipped
  check-name:
    description: "A name of a check that has to pass"
    required: false
    default: ""
  check-regexp:
    description: "Filter checks to wait using Regexp"
    required: false
    default: ""
  ref:
    description: "A git ref to be checked: branch/tag/commit sha"
    required: true
  repo-token:
    description: "A GitHub token for the repo"
    required: false
    default: ""
  wait-interval:
    description: "Seconds to wait between Checks API requests"
    required: false
    default: "10"
  running-workflow-name:
    description: "Name of the workflow to be ignored (the one who is waiting for the rest)"
    required: false
    default: ""
  verbose:
    description: "Print logs if true"
    required: false
    default: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.allowed-conclusions }}
    - ${{ inputs.check-name }}
    - ${{ inputs.check-regexp }}
    - ${{ inputs.ref }}
    - ${{ inputs.repo-token }}
    - ${{ inputs.verbose }}
    - ${{ inputs.wait-interval }}
    - ${{ inputs.running-workflow-name }}
branding:
  icon: "check-circle"
  color: "green"
