name: Delete Release
on:
  workflow_dispatch:  # manually run
    inputs:
      RELEASE_VERSION:
        description: 'Set the version of the tag/release to be removed'
        required: true
jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: ${{ env.RELEASE_VERSION }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
