name: RSpec tests

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

  workflow_dispatch:

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
        ruby-version: 2.7
        bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: cd app && bundle exec rspec
